site_name: Scene Forge
nav:
- Getting Started:
  - What is Scene Forge?: 01_index.md
  - Getting Started: 02_Getting_Started.md
- Systems:
  - Prototype Objects: 03_Prototype_Objects.md
  - Collections: 04_Collections.md
  - Objects Convert: 05_Object_Convert.md
  - Quick Convert: 06_Quick_Convert.md
  - Object Presets: 07_Object_Presets.md
  - Add LOD Group: 08_Add_LOD_Group.md
  - Composition Guides: 09_Composition_Guides.md
  - Line Array: 10_Line_Array.md
  - Radial Array: 11_Radial_Array.md
  - Random Rottation: 12_Random_Rotation.md
  - Random Scale: 13_Random_Scale.md
  - Time of Day Presets: 14_Time_of_Day_Preset.md
- Scattering:
  - Point Scatter: 15_Point_Scatter.md
  - Area Scatter: 16_Area_Scatter.md
  - Mesh Scatter: 17_Mesh_Scatter.md
- FAQ:
  - Package Clean Up: 18_Package_Clean_Up.md
  - Shortcuts: 19_Shortcuts.md
  - FAQ: 20_FAQ.md
  - Reporting Issues: 21_Reporting_Issues.md

theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - admonition